name: Install eclint
description: Installs eclint from cache, or builds it

inputs:
  eclint-version:
    required: false
    description: "eclint version to use"
    default: "v0.5.1"

runs:
  using: "composite"
  steps:
    - name: Cache eclint binary
      id: cache-eclint
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ~/.local/bin/eclint
        key: eclint-${{ inputs.eclint-version }}-${{ runner.os }}-${{ runner.arch }}
    - name: Setup go
      if: steps.cache-eclint.outputs.cache-hit != 'true'
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: '1.24'
        cache: false
    - name: Install eclint
      if: steps.cache-eclint.outputs.cache-hit != 'true'
      run: GOBIN=${HOME}/.local/bin go install gitlab.com/greut/eclint/cmd/eclint@${ECLINT_VERSION}
      shell: bash
      env:
        ECLINT_VERSION: ${{ inputs.eclint-version }}
    - name: Configure gradle
      run: echo "lucene.tool.eclint=eclint" >> build-options.local.properties
      shell: bash
